/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppLabRouteImport } from './routes/_app/lab'
import { Route as AppLabelsRouteImport } from './routes/_app/labels'
import { Route as AppPamphletRouteImport } from './routes/_app/pamphlet'
import { Route as AppPreorderRouteImport } from './routes/_app/preorder'
import { Route as AppTransparencyRouteImport } from './routes/_app/transparency'
import { Route as AppLabIndexRouteImport } from './routes/_app/lab/index'
import { Route as AppLabWholesaleRouteImport } from './routes/_app/lab/wholesale'
import { Route as AppProductsSkuRouteImport } from './routes/_app/products.$sku'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsRoute = AppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppPamphletRoute = AppPamphletRouteImport.update({
  id: '/pamphlet',
  path: '/pamphlet',
  getParentRoute: () => AppRoute,
} as any)
const AppPreorderRoute = AppPreorderRouteImport.update({
  id: '/preorder',
  path: '/preorder',
  getParentRoute: () => AppRoute,
} as any)
const AppTransparencyRoute = AppTransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => AppRoute,
} as any)
const AppLabIndexRoute = AppLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLabRoute,
} as any)
const AppLabWholesaleRoute = AppLabWholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => AppLabRoute,
} as any)
const AppProductsSkuRoute = AppProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/cart': typeof AppCartRoute
  '/catalog': typeof AppCatalogRoute
  '/lab': typeof AppLabRouteWithChildren
  '/labels': typeof AppLabelsRoute
  '/pamphlet': typeof AppPamphletRoute
  '/preorder': typeof AppPreorderRoute
  '/transparency': typeof AppTransparencyRoute
  '/lab/wholesale': typeof AppLabWholesaleRoute
  '/products/$sku': typeof AppProductsSkuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lab/': typeof AppLabIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/cart': typeof AppCartRoute
  '/catalog': typeof AppCatalogRoute
  '/labels': typeof AppLabelsRoute
  '/pamphlet': typeof AppPamphletRoute
  '/preorder': typeof AppPreorderRoute
  '/transparency': typeof AppTransparencyRoute
  '/': typeof AppIndexRoute
  '/lab/wholesale': typeof AppLabWholesaleRoute
  '/products/$sku': typeof AppProductsSkuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/lab': typeof AppLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/lab': typeof AppLabRouteWithChildren
  '/_app/labels': typeof AppLabelsRoute
  '/_app/pamphlet': typeof AppPamphletRoute
  '/_app/preorder': typeof AppPreorderRoute
  '/_app/transparency': typeof AppTransparencyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lab/wholesale': typeof AppLabWholesaleRoute
  '/_app/products/$sku': typeof AppProductsSkuRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/lab/': typeof AppLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/cart'
    | '/catalog'
    | '/lab'
    | '/labels'
    | '/pamphlet'
    | '/preorder'
    | '/transparency'
    | '/lab/wholesale'
    | '/products/$sku'
    | '/api/auth/$'
    | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/cart'
    | '/catalog'
    | '/labels'
    | '/pamphlet'
    | '/preorder'
    | '/transparency'
    | '/'
    | '/lab/wholesale'
    | '/products/$sku'
    | '/api/auth/$'
    | '/lab'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/about'
    | '/_app/cart'
    | '/_app/catalog'
    | '/_app/lab'
    | '/_app/labels'
    | '/_app/pamphlet'
    | '/_app/preorder'
    | '/_app/transparency'
    | '/_app/'
    | '/_app/lab/wholesale'
    | '/_app/products/$sku'
    | '/api/auth/$'
    | '/_app/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab': {
      id: '/_app/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels': {
      id: '/_app/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AppLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pamphlet': {
      id: '/_app/pamphlet'
      path: '/pamphlet'
      fullPath: '/pamphlet'
      preLoaderRoute: typeof AppPamphletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preorder': {
      id: '/_app/preorder'
      path: '/preorder'
      fullPath: '/preorder'
      preLoaderRoute: typeof AppPreorderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transparency': {
      id: '/_app/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof AppTransparencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab/': {
      id: '/_app/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof AppLabIndexRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/lab/wholesale': {
      id: '/_app/lab/wholesale'
      path: '/wholesale'
      fullPath: '/lab/wholesale'
      preLoaderRoute: typeof AppLabWholesaleRouteImport
      parentRoute: typeof AppLabRoute
    }
    '/_app/products/$sku': {
      id: '/_app/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof AppProductsSkuRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppLabRouteChildren {
  AppLabWholesaleRoute: typeof AppLabWholesaleRoute
  AppLabIndexRoute: typeof AppLabIndexRoute
}

const AppLabRouteChildren: AppLabRouteChildren = {
  AppLabWholesaleRoute: AppLabWholesaleRoute,
  AppLabIndexRoute: AppLabIndexRoute,
}

const AppLabRouteWithChildren =
  AppLabRoute._addFileChildren(AppLabRouteChildren)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppCartRoute: typeof AppCartRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppLabRoute: typeof AppLabRouteWithChildren
  AppLabelsRoute: typeof AppLabelsRoute
  AppPamphletRoute: typeof AppPamphletRoute
  AppPreorderRoute: typeof AppPreorderRoute
  AppTransparencyRoute: typeof AppTransparencyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductsSkuRoute: typeof AppProductsSkuRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppCartRoute: AppCartRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppLabRoute: AppLabRouteWithChildren,
  AppLabelsRoute: AppLabelsRoute,
  AppPamphletRoute: AppPamphletRoute,
  AppPreorderRoute: AppPreorderRoute,
  AppTransparencyRoute: AppTransparencyRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductsSkuRoute: AppProductsSkuRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
